#!/usr/bin/env python3
"""Generate the keyboard layout for every platform from runes.py.

Run `python3 build.py` and everything under dist/ is rewritten. Never
edit dist/ by hand -- change the table in runes.py and rebuild, so the
four platforms cannot drift apart.
"""

import pathlib

import runes

DIST = pathlib.Path(__file__).parent / "dist"


def cp(ch):
    """Unicode codepoint as bare lowercase hex, e.g. 'ᛆ' -> '16c6'."""
    return f"{ord(ch):04x}"


# --------------------------------------------------------------------------
# Linux -- XKB symbols file
# --------------------------------------------------------------------------

def build_linux():
    lines = [
        "// Medieval Norwegian runes, laid over the Norwegian (no) pc105 layout.",
        "//",
        "// GENERATED by build.py from runes.py -- do not edit by hand.",
        "//",
        "// Level 1 is the strict 1:1 Norwegian alphabet, æ ø å included, each on",
        "// the key you already press for it. Level 2 (shift) carries runic",
        "// punctuation and the Younger Futhark variant forms.",
        "",
        "default partial alphanumeric_keys",
        'xkb_symbols "basic" {',
        "",
        "    // Inherit digits, modifiers and the non-letter keys from Norwegian.",
        '    include "no(basic)"',
        "",
        f'    name[Group1] = "{runes.LAYOUT_NAME}";',
        "",
    ]
    for latin, base, shift, xkb, _mac, _sc, _vk, note in runes.KEYS:
        lines.append(
            f"    key <{xkb}> {{ [ U{cp(base).upper()}, U{cp(shift).upper()} ] }};"
            f"  // {latin}  {base} | {shift} {note}"
        )
    lines.append("")
    lines.append("    // Latin punctuation unshifted so ordinary sentences still work.")
    for latin, base, shift, xkb, _mac, _sc, _vk, note in runes.PUNCT_KEYS:
        name = {",": "comma", ".": "period", "-": "minus"}[latin]
        lines.append(
            f"    key <{xkb}> {{ [ {name}, U{cp(shift).upper()} ] }};"
            f"  // {latin} | {shift} {note}"
        )
    lines.append("};")
    write("linux/runic", "\n".join(lines) + "\n")


LINUX_INSTALL = """#!/usr/bin/env bash
# Install the runic keyboard layout for the current user. No root needed.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)/runic"
DEST="${XDG_CONFIG_HOME:-$HOME/.config}/xkb/symbols"

mkdir -p "$DEST"
cp "$SRC" "$DEST/runic"
echo "Installed to $DEST/runic"

if command -v xkbcli >/dev/null && xkbcli compile-keymap --layout runic >/dev/null 2>&1; then
    echo "Layout compiles cleanly."
else
    echo "Warning: layout did not compile. You need libxkbcommon 1.0 or newer." >&2
fi

cat <<'EOF'

Now activate it. User-level layouts do not appear in most desktop
settings GUIs -- that list is built from the system-wide evdev.xml -- so
set it by config or command:

  COSMIC   edit ~/.config/cosmic/com.system76.CosmicComp/v1/xkb_config
           and set  layout: "runic"   (or "no,runic" for two groups)
  Sway     input * xkb_layout "no,runic"
  Hyprland kb_layout = no,runic
  GNOME/KDE these read the system list; either install system-wide (see
           README) or use setxkbmap under X11:  setxkbmap runic

To switch with a key, either add an XKB group toggle option
(grp:alt_shift_toggle) or bind a chord to rune-layout-toggle -- see README.
EOF
"""


# --------------------------------------------------------------------------
# macOS -- .keylayout XML
# --------------------------------------------------------------------------

# Keys that are not letters still need to produce something, or they go dead.
MAC_BASE = {
    49: " ", 36: "\n", 48: "\t",
    18: "1", 19: "2", 20: "3", 21: "4", 23: "5",
    22: "6", 26: "7", 28: "8", 25: "9", 29: "0",
    27: "+", 24: "\\", 30: "¨", 42: "'", 50: "|",
}
MAC_SHIFT = {
    49: " ", 36: "\n", 48: "\t",
    18: "!", 19: '"', 20: "#", 21: "¤", 23: "%",
    22: "&", 26: "/", 28: "(", 25: ")", 29: "=",
    27: "?", 24: "`", 30: "^", 42: "*", 50: "§",
}


def esc(ch):
    """.keylayout output attribute. Escape XML metacharacters, and send
    anything non-ASCII as a numeric reference so the file stays 7-bit."""
    if ch == "&":
        return "&amp;"
    if ch == "<":
        return "&lt;"
    if ch == ">":
        return "&gt;"
    if ch == '"':
        return "&quot;"
    if ch == "\n":
        return "&#x000D;"
    if ch == "\t":
        return "&#x0009;"
    if ord(ch) > 127:
        return f"&#x{ord(ch):04X};"
    return ch


def build_macos():
    base, shift = dict(MAC_BASE), dict(MAC_SHIFT)
    for latin, b, s, _xkb, mac, _sc, _vk, _note in runes.ALL_KEYS:
        base[mac] = b
        shift[mac] = s

    def keymap(index, table):
        rows = [f'    <keyMap index="{index}">']
        for code in sorted(table):
            rows.append(f'      <key code="{code}" output="{esc(table[code])}"/>')
        rows.append("    </keyMap>")
        return "\n".join(rows)

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "file://localhost/System/Library/DTDs/KeyboardLayout.dtd">
<!-- GENERATED by build.py from runes.py - do not edit by hand. -->
<keyboard group="126" id="-31337" name="{runes.LAYOUT_NAME}" maxout="1">
  <layouts>
    <layout first="0" last="17" mapSet="runic" modifiers="mods"/>
  </layouts>
  <modifierMap id="mods" defaultIndex="0">
    <keyMapSelect mapIndex="0">
      <modifier keys=""/>
      <modifier keys="command"/>
      <modifier keys="caps"/>
    </keyMapSelect>
    <keyMapSelect mapIndex="1">
      <modifier keys="anyShift"/>
      <modifier keys="anyShift caps"/>
    </keyMapSelect>
  </modifierMap>
  <keyMapSet id="runic">
{keymap(0, base)}
{keymap(1, shift)}
  </keyMapSet>
</keyboard>
"""
    write("macos/Runic.keylayout", xml)


# --------------------------------------------------------------------------
# Windows -- MSKLC source (.klc)
# --------------------------------------------------------------------------

def build_windows_klc():
    head = f"""KBD\t{runes.SHORT_NAME}\t"{runes.LAYOUT_NAME}"

COPYRIGHT\t"Public domain"
COMPANY\t"norwegian-runic-keyboard"
LOCALENAME\t"nb-NO"
LOCALEID\t"00000414"
VERSION\t1.0
SHIFTSTATE

0\t//Column 4
1\t//Column 5 : Shft

LAYOUT\t\t;an extra '@' at the end is a dead key

//SC\tVK_\t\tCap\t0\t1
//--\t----\t\t----\t----\t----
"""
    rows = []
    for latin, b, s, _xkb, _mac, sc, vk, note in runes.ALL_KEYS:
        rows.append(f"{sc}\t{vk}\t\t0\t{cp(b)}\t{cp(s)}\t// {latin}  {b} {s}  {note}")
    tail = """
39\tSPACE\t\t0\t0020\t0020\t// space

DESCRIPTIONS

0409\t%s

LANGUAGENAMES

0409\tNorwegian Runic

ENDKBD
""" % runes.LAYOUT_NAME
    write("windows/runic.klc", head + "\n".join(rows) + tail)


# --------------------------------------------------------------------------
# Windows -- AutoHotkey v2 (no admin, no compiler)
# --------------------------------------------------------------------------

def build_windows_ahk():
    lines = [
        "#Requires AutoHotkey v2.0",
        ";",
        "; Medieval Norwegian runes for Windows, without a compiled layout.",
        "; GENERATED by build.py from runes.py -- do not edit by hand.",
        ";",
        "; Ctrl+Alt+R toggles runic mode on and off. (Win+R is Windows' own Run",
        "; dialog, so this uses Ctrl+Alt+R instead of the Super+R used on Linux.)",
        ";",
        "; Keys are bound by scan code, so this works whatever layout is active --",
        "; but the letters land in Norwegian pc105 positions, so æ ø å are where a",
        "; Norwegian keyboard puts them.",
        "",
        "global RunicMode := false",
        "",
        "^!r:: {",
        "    global RunicMode",
        "    RunicMode := !RunicMode",
        '    ToolTip(RunicMode ? "Runic" : "Norsk")',
        "    SetTimer(() => ToolTip(), -900)",
        "}",
        "",
        "#HotIf RunicMode",
    ]
    for latin, b, s, _xkb, _mac, sc, _vk, note in runes.ALL_KEYS:
        lines.append(f'sc0{sc}::SendText("{b}")        ; {latin} -> {b}')
        lines.append(f'+sc0{sc}::SendText("{s}")       ; shift -> {s} {note}')
    lines += ["#HotIf", ""]
    write("windows/runic.ahk", "\n".join(lines))


# --------------------------------------------------------------------------

def write(relpath, text):
    path = DIST / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(DIST.parent)}  ({len(text)} bytes)")


def main():
    runes.check()
    print(f"{len(runes.TABLE)} letters, distinct and reversible. Generating:")
    build_linux()
    write("linux/install.sh", LINUX_INSTALL)
    (DIST / "linux/install.sh").chmod(0o755)
    build_macos()
    build_windows_klc()
    build_windows_ahk()
    print("Done.")


if __name__ == "__main__":
    main()
