#!/usr/bin/env python3
"""Generate a runic typeface from skeletons, parametrically.

Runes are a stave plus branches, which means they can be *described*
rather than drawn: each glyph below is a list of strokes on a shared
grid, and the outlines are generated by offsetting those centrelines.
Curvature, weight and spacing are dials, so a redesign is a rebuild
rather than a redraw.

Skeletons were derived from Noto Sans Runic's own outlines (cap height
714, stroke weight 92) so the letterforms stay correct; the parameters
are then free to depart from it.

Two things matter for the result not looking broken:

* A shape that turns a corner is ONE path offset as a whole, with
  mitred joins. Offsetting each segment separately and stacking them
  leaves a notch on the outside of every corner.
* Overlapping strokes are not booleaned. TrueType fills by nonzero
  winding, so contours wound the same direction merge for free -- which
  is why this needs no boolean-operations library.
"""

import math

CAP = 714          # cap height, matching Noto Sans Runic
UPEM = 1000

# --- the dials -------------------------------------------------------
WEIGHT = 76        # stroke thickness. Noto is 92; lighter reads airier.
CURVE = 0.60       # 0 = straight branches, 1 = strongly bowed
SIDE = 120         # sidebearing each side. Noto is ~96; wider = airier.
DOT_R = 52         # radius of the dot on dotted runes
DOT_X = 108        # how far the dot sits from the stave centre
SEGMENTS = 20      # sampling resolution for curved strokes
MITER_LIMIT = 3.4  # beyond this a sharp corner bevels instead of spiking

# --- style switches ---------------------------------------------------
# DETACH lifts every limb off the stave: a stroke that begins or ends on
# the stave centreline is trimmed so its edge stops DETACH units short of
# the stave's edge. The freed end is a free end, so it takes a round cap.
DETACH = 0

# SERIF adds feet and heads wherever a stave or vertical meets the
# baseline or the cap height. Two styles:
#   "slab"       a plain bar -- the typewriter look
#   "bracketed"  a thin base whose sides curve up into the stem, the way
#                an antikva (Times) serif is cut
SERIF = False
SERIF_STYLE = "slab"
SERIF_LEN = 110      # half-length of the foot
SERIF_H = 30         # thickness of the bracketed serif's base
BRACKET_H = 150      # how far up the stem the bracket curve reaches

# CONTRAST modulates the stroke: 1.0 is monoline; lower values thin the
# horizontals while stems stay at WEIGHT. 0.55 reads as an antikva.
CONTRAST = 1.0

# STRESS_ANGLE tilts the thin axis, in degrees. 0 is vertical stress (thin
# exactly at the top of a curve, the Times model); negative angles lean the
# nib the way a right hand holds it (old-style); positive leans it the
# other way. Only matters when CONTRAST < 1.
STRESS_ANGLE = 0

# SLANT shears the whole glyph for an italic, in degrees clockwise.
SLANT = 0

# Which skeleton set the font is built from:
#   "neweuropean"  the orthogonal construction: every bend a right angle,
#                  arms curved, h a closed box, d and t bracketed
#   "traditional"  the diagonal skeletons derived from Noto Sans Runic:
#                  arms straight, h an X, d a single left arm, r a bowl
#                  with a leg -- the shapes as the tradition draws them
#   "hybrid"       traditional arms and crosses, ny-europeisk curves:
#                  bowls, arches and hooks are round, arms stay straight
SKELETON = "neweuropean"

# A flat that is flush with the baseline or cap is placed by its OUTER
# edge at the thickness contrast actually leaves it -- otherwise the
# full-weight stave underneath pokes through the thinned flat.
H_TOP = CAP - max(1, round(WEIGHT * CONTRAST)) // 2


def _cfac(nx, ny=0.0):
    """Stroke-width factor for a segment with unit normal (nx, ny).

    Elliptical -- the width a broad nib of ratio CONTRAST would leave --
    so it changes smoothly through a curve; a linear blend kinks at the
    corner arcs. STRESS_ANGLE rotates the nib, moving where on a curve
    the thin point falls."""
    if CONTRAST >= 1.0:
        return 1.0
    a = math.radians(STRESS_ANGLE)
    nr = nx * math.cos(a) + ny * math.sin(a)
    return math.sqrt(nr * nr + CONTRAST * CONTRAST * (1.0 - nr * nr))
CAP_TOL = 30       # how close to the baseline or cap height still counts as
                   # "landing on the line", and so stays flat-ended
RADIUS = 40        # default corner radius on the centreline. 0 = sharp
                   # mitre; small = a hard corner; large = a soft sweep.
                   # Any single point may override it as (x, y, r).

# --- skeletons -------------------------------------------------------
# x is relative to the stave centre; y is absolute from the baseline.
#   S                 full-height stave at x=0
#   V x y0 y1         vertical segment
#   L x0 y0 x1 y1     straight stroke
#   C x0 y0 x1 y1 [s] bowed stroke; s=-1 bows the other way. Branches
#                     bow AWAY from the stave, or they close over the dot
#                     that separates g from k and v from f.
#   P [pts]           connected path, mitred at every corner. Entries are
#                     (x,y), (x,y,r) to give that one corner its own
#                     radius, or ("c",x,y,sign) to bow into that point.
#   A [p0,ctrl,p2]    smooth arc through a quadratic control point
#   O x y r           dot
#   D x y r           filled disc (the bowl of c)
#   R x y r           ring -- a circle STROKED at the font's weight, not
#                     filled. Punctuation uses this so a full stop is built
#                     the same way as every other mark: a line, not a blob.
# --- the width module -------------------------------------------------
# Every glyph's ink is one of three widths, and the reaches are derived
# from them rather than chosen by eye: a branch springing from the stave
# reaches W - WEIGHT, and a shape spanning both sides reaches
# (W - WEIGHT)/2.
#
# i is the one exception. It is a bare stave, so its ink IS the stroke
# width; nothing can widen it without making it a different letter.
#
# A corner is a full quarter circle when its radius equals half the
# shorter adjacent segment, so side branches are built with equal legs to
# land exactly there.
# A flat stroke that defines the top or bottom of a glyph is positioned by
# its OUTER edge, not its centreline: a horizontal centred on the cap would
# put half the stroke above it and leave a step where it meets the stave.
# Curves are the exception -- u, w and y overshoot on purpose, or round
# shapes read short next to flat ones.
FLAT_TOP, FLAT_BOTTOM = CAP - WEIGHT // 2, WEIGHT // 2
OVERSHOOT = 12                       # ~1.7% of cap height
ARCH = CAP + OVERSHOOT - WEIGHT // 2  # centreline apex of u, w and y, so
                                      # their ink clears the flat tops by
                                      # OVERSHOOT rather than half a stroke

NARROW, MEDIUM, WIDE = 240, 480, 640
ONE_M, ONE_W = 404, 564              # reach from the stave, one side only
SYM_M, SYM_W = 202, 282              # reach either side of centre
# Dots are positioned FROM the geometry they sit in, never by absolute
# coordinates: a dot placed by hand stays put when a reach changes and
# ends up colliding with the stroke it was meant to sit beside.
DOT_CLEAR = 26                       # gap from a dot's edge to any stroke
ARM_R = 115                          # corner radius of the arm in f v k g
BOWL_R = 142                         # corner radius of the bowls in b p

# --- b and p ----------------------------------------------------------
# BP_SPACE pulls the bowls back from the cap and the baseline, so the stave
# shows above and below instead of the bowls filling the whole height.
# Zero gives full-height bowls.
#
# BP_MIDDLE decides what happens where the two bowls meet:
#   "shared"  one line, both bowls ending on it        <- no fusion possible
#   "split"   two arms a real BP_GAP apart
#   "merge"   two arms close together; if that gap is under WEIGHT they
#             fuse into one bar of nearly double thickness, which qa.py
#             reports rather than letting it pass
BP_SPACE = 110
BP_MIDDLE = "shared"
BP_GAP = 170
ATTACH_MID = 357                     # where branches meet the stave

# j is two opposed hooks and the only rune that touches neither line.
#   "full"    stretched so it sits on the baseline and reaches the cap
#   "centred" its own proportions, centred between the two lines
#   "float"   as drawn before: hanging from the cap
J_STYLE = "full"
if J_STYLE == "full":
    _J = (WEIGHT // 2, 251, 464, CAP - WEIGHT // 2)
elif J_STYLE == "centred":
    _J = (102, 272, 442, 612)
else:
    _J = (166, 336, 506, 676)

_BP_TOP = CAP - BP_SPACE - WEIGHT // 2      # placed by the bowls' OUTER edge
_BP_BOT = BP_SPACE + WEIGHT // 2
if BP_MIDDLE == "shared":
    _BP_TI = _BP_BI = ATTACH_MID
elif BP_MIDDLE == "split":
    _BP_TI, _BP_BI = ATTACH_MID + BP_GAP // 2, ATTACH_MID - BP_GAP // 2
else:
    _BP_TI, _BP_BI = ATTACH_MID + 35, ATTACH_MID - 35
# Radius is half the bowl's height, so each outer edge stays a single arc.
_BP_RT = round((_BP_TOP - _BP_TI) / 2)
_BP_RB = round((_BP_BI - _BP_BOT) / 2)
# A dot has to fit the bowl it sits in, and BP_SPACE can make that bowl
# small, so its radius is capped by the space available rather than fixed.
_P_DOT = max(24, min(DOT_R, min(_BP_RT, _BP_RB) - WEIGHT // 2 - DOT_CLEAR))

STUB_N, STUB_R_N = 164, 82           # narrow side branch -> quarter circle
STUB_M, STUB_R_M = 202, 101          # medium side branch
GAP = 160                            # between the arms of f and v; also makes
                                     # kaun's arm identical to fe's inner one

GLYPHS = {
    # --- narrow, ink 240 ---------------------------------------------
    "a": [("S",), ("P", [(0, 430), (-STUB_N, 430, STUB_R_N), (-STUB_N, 266)])],
    "c": [("D", 0, 366, 120), ("V", 0, 470, CAP)],
    # The dot sets this glyph's width, so its position comes from NARROW.
    "e": [("S",), ("O", NARROW - WEIGHT // 2 - DOT_R, 370, DOT_R)],
    "i": [("S",)],
    "l": [("S",), ("P", [(0, 660), (STUB_N, 660, STUB_R_N), (STUB_N, 496)])],
    "n": [("S",), ("P", [(0, 430), (STUB_N, 430, STUB_R_N), (STUB_N, 266)])],
    "o": [("S",), ("P", [(0, 520), (-STUB_N, 520, STUB_R_N), (-STUB_N, 356)]),
          ("P", [(0, 290), (-STUB_N, 290, STUB_R_N), (-STUB_N, 126)])],
    "å": [("S",), ("P", [(0, 520), (STUB_N, 520, STUB_R_N), (STUB_N, 356)]),
          ("P", [(0, 290), (STUB_N, 290, STUB_R_N), (STUB_N, 126)])],

    # --- medium, ink 480 ---------------------------------------------
    # Bowl radius is half the bowl's height, so each outer edge is one
    # continuous semicircle rather than two corners with a flat between.
    "b": [("S",),
          ("P", [(0, _BP_TOP), (ONE_M, _BP_TOP, _BP_RT), (ONE_M, _BP_TI, _BP_RT),
                 (0, _BP_TI)]),
          ("P", [(0, _BP_BI), (ONE_M, _BP_BI, _BP_RB), (ONE_M, _BP_BOT, _BP_RB),
                 (0, _BP_BOT)])],
    "d": [("S",), ("P", [(-SYM_M, 476), (-SYM_M, H_TOP, 100), (SYM_M, H_TOP, 100),
                         (SYM_M, 476)]),
          ("O", WEIGHT // 2 + DOT_CLEAR + DOT_R, 340, DOT_R)],
    # On the arm's own arc centre, so it stays in the crook at any reach.
    "g": [("S",), ("P", [(0, 300), (ONE_M, 300, ARM_R), (ONE_M, 700)]),
          ("O", ONE_M - ARM_R, 300 + ARM_R, DOT_R)],
    "h": [("S",), ("P", [(-SYM_M, 250, 100), (SYM_M, 250, 100), (SYM_M, 490, 100),
                         (-SYM_M, 490, 100), (-SYM_M, 250)])],
    "j": [("P", [(60, _J[3]), (-SYM_M, _J[3], 125), (-SYM_M, _J[1], 125), (60, _J[1])]),
          ("P", [(-60, _J[0]), (SYM_M, _J[0], 125), (SYM_M, _J[2], 125), (-60, _J[2])])],
    "k": [("S",), ("P", [(0, 300), (ONE_M, 300, ARM_R), (ONE_M, 700)])],
    "p": [("S",),
          ("P", [(0, _BP_TOP), (ONE_M, _BP_TOP, _BP_RT), (ONE_M, _BP_TI, _BP_RT),
                 (0, _BP_TI)]),
          ("P", [(0, _BP_BI), (ONE_M, _BP_BI, _BP_RB), (ONE_M, _BP_BOT, _BP_RB),
                 (0, _BP_BOT)]),
          ("O", ONE_M - _BP_RT, _BP_TOP - _BP_RT, _P_DOT),
          ("O", ONE_M - _BP_RB, _BP_BOT + _BP_RB, _P_DOT)],
    # A square bowl, so one radius is half of both sides at once.
    "q": [("S",), ("P", [(0, H_TOP), (-ONE_M, H_TOP, 183), (-ONE_M, 310, 183), (0, 310)])],
    "r": [("S",), ("P", [(0, H_TOP), (ONE_M, H_TOP, 202), (ONE_M, 0)]),
          ("P", [(0, 470), (ONE_M, 470)])],
    "s": [("P", [(-SYM_M, CAP), (-SYM_M, 392), (SYM_M, 392), (SYM_M, 0)])],
    "t": [("S",), ("P", [(-SYM_M, 476), (-SYM_M, H_TOP, 100), (SYM_M, H_TOP, 100),
                         (SYM_M, 476)])],
    "z": [("V", 0, 300, CAP),
          ("P", [(-SYM_M, 470), (-SYM_M, 300, 85), (SYM_M, 300, 85), (SYM_M, 470)])],
    "æ": [("S",), ("P", [(0, 430), (-STUB_M, 430, STUB_R_M), (-STUB_M, 228)]),
          ("P", [(0, 430), (STUB_M, 430, STUB_R_M), (STUB_M, 632)])],
    # Pulled apart to 560/250: at 520/290 the upper stub's tail ended 28
    # above the lower stub's arm, and a 76-wide stroke fused the two.
    "ø": [("S",), ("P", [(0, 560), (-STUB_M, 560, STUB_R_M), (-STUB_M, 358)]),
          ("P", [(0, 250), (-STUB_M, 250, STUB_R_M), (-STUB_M, 48)]),
          ("P", [(0, 560), (STUB_M, 560, STUB_R_M), (STUB_M, 358)]),
          ("P", [(0, 250), (STUB_M, 250, STUB_R_M), (STUB_M, 48)])],

    # --- wide, ink 640 -----------------------------------------------
    # The arms are GAP apart on the straights and GAP apart in radius, so
    # both arcs share a centre and the gap never varies.
    "f": [("S",), ("P", [(0, 300), (ONE_M, 300, ARM_R), (ONE_M, 700)]),
          ("P", [(0, 140), (ONE_W, 140, 275), (ONE_W, 700)])],
    "m": [("S",), ("P", [(-SYM_W, 700), (-SYM_W, 470, 115), (SYM_W, 470, 115),
                         (SYM_W, 700)])],
    # Radius equals half the width, so the cap is a single semicircle.
    "u": [("P", [(-SYM_W, 0), (-SYM_W, ARCH, SYM_W), (SYM_W, ARCH, SYM_W), (SYM_W, 0)])],
    "v": [("S",), ("P", [(0, 300), (ONE_M, 300, ARM_R), (ONE_M, 700)]),
          ("P", [(0, 140), (ONE_W, 140, 275), (ONE_W, 700)]),
          ("O", ONE_M - ARM_R, 300 + ARM_R, DOT_R)],
    "w": [("P", [(-SYM_W, 0), (-SYM_W, ARCH, SYM_W), (SYM_W, ARCH, SYM_W), (SYM_W, 0)]),
          ("P", [(-SYM_W, 330), (122, 330, 110), (122, 0)])],
    "x": [("P", [(-SYM_M, CAP), (-SYM_M, 392), (SYM_M, 392), (SYM_M, 0)]),
          ("L", -SYM_W, 600, 2, 600), ("L", -2, 120, SYM_W, 120)],
    "y": [("P", [(-SYM_W, 0), (-SYM_W, ARCH, SYM_W), (SYM_W, ARCH, SYM_W), (SYM_W, 0)]),
          ("O", 0, 300, DOT_R)],
}

# The runic word dividers keep their solid dots -- that is how they were
# cut. Latin punctuation is drawn as a ring instead, so a full stop reads
# as a stroke like everything else in the face rather than a filled blob.
HOOK_R = 85          # the hook's corner radius, shared with j
RING_R = 62          # centreline radius when the mark is drawn as a ring
RING_Y = RING_R + WEIGHT // 2      # sits it on the baseline

# How the mark under . ! and ? is drawn:
#   "connected"  a disc with the line growing out of it, exactly the way c
#                is built -- one shape, not a line hovering over a dot
#   "dot"        a separate filled dot, as e d g p v y carry theirs
#   "ring"       a circle stroked at the font's weight
PUNCT_DOT = "connected"

MARK_R = 120         # matches c's disc, and makes the mark exactly NARROW wide
MARK_OVERLAP = 16    # how far the line reaches into the disc, as in c

if PUNCT_DOT == "connected":
    _MARK = ("D", 0, MARK_R, MARK_R)
    _STEM_FOOT = MARK_R * 2 - MARK_OVERLAP        # ends inside the disc
elif PUNCT_DOT == "ring":
    _MARK = ("R", 0, RING_R + WEIGHT // 2, RING_R)
    _STEM_FOOT = RING_R * 2 + WEIGHT + DOT_CLEAR
else:
    _MARK = ("O", 0, DOT_R, DOT_R)
    _STEM_FOOT = DOT_R * 2 + DOT_CLEAR + WEIGHT // 2


# The traditional skeletons, taken from Noto Sans Runic's own outlines
# (cap 714) before the orthogonal rebuild. Diagonals are the point:
# rune carvers avoided horizontals, so these shapes are mostly stave
# plus slanted branch. Widths follow the letterforms, not the module.
GLYPHS_TRADITIONAL = {
    "a": [("S",), ("L", 0, 346, -201, 263)],
    "b": [("S",), ("P", [(0, 714), (315, 508), (0, 357), (315, 218), (0, 0)])],
    "c": [("D", 0, 366, 120), ("V", 0, 470, CAP)],
    "d": [("S",), ("L", 0, 700, -201, 588), ("O", 108, 340, DOT_R)],
    "e": [("S",), ("O", 150, 370, DOT_R)],
    "f": [("S",), ("L", 0, 480, 255, 708), ("L", 0, 289, 476, 708)],
    "g": [("S",), ("L", 0, 316, 366, 708), ("O", 178, 560, DOT_R)],
    "h": [("S",), ("L", -195, 219, 197, 482), ("L", -195, 482, 197, 219)],
    "i": [("S",)],
    "j": [("P", [(10, 714), (-95, 590), (10, 462)]),
          ("P", [(-10, 252), (95, 380), (-10, 508)])],
    "k": [("S",), ("L", 0, 316, 366, 708)],
    "l": [("S",), ("L", 0, 672, 196, 584)],
    "m": [("S",), ("L", 0, 480, -269, 700), ("L", 0, 480, 269, 700)],
    "n": [("S",), ("L", 0, 337, 195, 249)],
    "o": [("S",), ("L", 0, 274, -201, 191), ("L", 0, 435, -201, 352)],
    "p": [("S",), ("P", [(0, 714), (315, 508), (0, 357), (315, 218), (0, 0)]),
          ("O", 150, 522, 46), ("O", 150, 202, 46)],
    "q": [("S",), ("P", [(0, 714), (-262, 478), (0, 228)])],
    "r": [("S",), ("P", [(0, 714), (275, 535), (0, 345), (300, 0)])],
    "s": [("P", [(-184, CAP), (-184, 268), (184, 479), (184, 0)])],
    "t": [("S",), ("L", 0, 700, -201, 588), ("L", 0, 700, 195, 585)],
    "u": [("P", [(-204, 0), (-204, CAP, 204), (204, CAP, 204), (204, 0)])],
    "v": [("S",), ("L", 0, 480, 255, 708), ("L", 0, 289, 476, 708),
          ("O", 150, 640, DOT_R)],
    "w": [("P", [(-240, 0), (-240, CAP, 205), (170, CAP, 205), (170, 0)]),
          ("P", [(-240, 381), (20, 250, 110), (20, 0)])],
    "x": [("P", [(-184, CAP), (-184, 268), (184, 479), (184, 0)]),
          ("L", -372, 600, 2, 600), ("L", -2, 120, 372, 120)],
    "y": [("P", [(-204, 0), (-204, CAP, 204), (204, CAP, 204), (204, 0)]),
          ("O", -6, 338, DOT_R)],
    "z": [("V", 0, 300, CAP), ("L", 0, 330, -196, 401), ("L", 0, 330, 204, 397)],
    "æ": [("S",), ("L", 0, 346, -201, 263), ("L", 0, 392, 204, 478)],
    "ø": [("S",), ("L", 0, 274, -201, 191), ("L", 0, 435, -201, 352),
          ("L", 0, 319, 202, 405), ("L", 0, 480, 202, 566)],
    "å": [("S",), ("L", 0, 427, 195, 339), ("L", 0, 266, 195, 178)],
}

# Hybrid: traditional wherever the part is an arm, stub or cross;
# ny-europeisk wherever it is a bowl, arch or hook. r keeps its
# traditional bowl-and-leg shape but the bowl's vertices are rounded.
GLYPHS_HYBRID = dict(GLYPHS_TRADITIONAL)
for _k in ("b", "p", "q", "u", "w", "y", "j"):
    GLYPHS_HYBRID[_k] = GLYPHS[_k]
GLYPHS_HYBRID["r"] = [("S",), ("P", [(0, 714), (275, 535, 120), (0, 345, 120),
                                     (300, 0)])]

if SKELETON == "traditional":
    GLYPHS = GLYPHS_TRADITIONAL
elif SKELETON == "hybrid":
    GLYPHS = GLYPHS_HYBRID

PUNCT = {
    "᛫": [("O", 0, 357, 46)],
    "᛬": [("O", 0, 214, 46), ("O", 0, 500, 46)],
    "᛭": [("V", 0, 100, 614), ("L", -190, 357, 190, 357)],
    ".": [_MARK],
    "!": [_MARK, ("V", 0, _STEM_FOOT, CAP)],
    # Built from the parts the alphabet already uses: a HOOK, like j's, with
    # a stem down to the ring. Every segment is at least twice HOOK_R long,
    # so no corner is clamped and all four match.
    # Two corners, not four: a short left leg, an ARCH over the top, and the
    # descender running straight down into the disc. The radius is half the
    # top's width, so the two corner arcs meet and the top is a single
    # semicircle -- the same construction as u, w and y.
    "?": [("D", 161, MARK_R, MARK_R),
          ("P", [(-161, 354), (-161, CAP - WEIGHT // 2, 161),
                 (161, CAP - WEIGHT // 2, 161), (161, _STEM_FOOT)])],
}


# --- geometry --------------------------------------------------------

def _bow(x0, y0, x1, y1, amount, n=SEGMENTS):
    """Sample a stroke bowed perpendicular to its chord."""
    dx, dy = x1 - x0, y1 - y0
    length = math.hypot(dx, dy) or 1.0
    nx, ny = -dy / length, dx / length
    sag = amount * length * 0.28
    return [(x0 + dx * (i / n) + nx * sag * (4 * (i / n) * (1 - i / n)),
             y0 + dy * (i / n) + ny * sag * (4 * (i / n) * (1 - i / n)))
            for i in range(n + 1)]


def _quad(p0, c, p2, n=SEGMENTS):
    """Quadratic Bezier through a control point -- used for the arched
    tops (t, d) and the valleys (m, z, j), which must read as one
    continuous curve rather than two lines meeting at a point."""
    pts = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        pts.append((u * u * p0[0] + 2 * u * t * c[0] + t * t * p2[0],
                    u * u * p0[1] + 2 * u * t * c[1] + t * t * p2[1]))
    return pts


def _expand(pts, curve):
    """Turn a path description into a dense polyline."""
    out = [pts[0]]
    for item in pts[1:]:
        if item and item[0] == "c":
            _, x, y, sign = item
            out += _bow(out[-1][0], out[-1][1], x, y, curve * sign)[1:]
        else:
            out.append(item)
    return out


def _fillet(pts, radius):
    """Round every corner of a centreline.

    `radius` is the default; a point given as (x, y, r) overrides it for
    that corner alone, so one shape can mix hard and soft turns. The arc
    is cut into the two adjacent segments, so the corner keeps its
    direction but stops being a point."""
    if len(pts) < 3:
        return pts
    out = [pts[0]]
    for i in range(1, len(pts) - 1):
        p, a, b = pts[i], pts[i - 1], pts[i + 1]
        here = p[2] if len(p) > 2 else radius
        if here <= 0:
            out.append(p)
            continue
        ux, uy = a[0] - p[0], a[1] - p[1]
        vx, vy = b[0] - p[0], b[1] - p[1]
        lu = math.hypot(ux, uy) or 1.0
        lv = math.hypot(vx, vy) or 1.0
        ux, uy, vx, vy = ux / lu, uy / lu, vx / lv, vy / lv
        cosang = max(-1.0, min(1.0, ux * vx + uy * vy))
        ang = math.acos(cosang)                 # interior angle at p
        if ang < 1e-3 or abs(math.pi - ang) < 1e-3:
            out.append(p)                        # straight through
            continue
        # A corner cannot eat more than half of either adjacent segment --
        # at exactly half, two corners on one segment meet and the segment
        # is fully consumed, which is the roundest a corner can get. Ask
        # for more and you simply get this.
        d = min(here / math.tan(ang / 2), lu * 0.5, lv * 0.5)
        r = d * math.tan(ang / 2)
        t1 = (p[0] + ux * d, p[1] + uy * d)
        t2 = (p[0] + vx * d, p[1] + vy * d)
        bx, by = ux + vx, uy + vy
        lb = math.hypot(bx, by) or 1.0
        centre = (p[0] + bx / lb * (r / math.sin(ang / 2)),
                  p[1] + by / lb * (r / math.sin(ang / 2)))
        a1 = math.atan2(t1[1] - centre[1], t1[0] - centre[0])
        a2 = math.atan2(t2[1] - centre[1], t2[0] - centre[0])
        sweep = (a2 - a1 + math.pi) % (2 * math.pi) - math.pi
        steps = max(6, int(abs(sweep) / 0.09))
        out += [(centre[0] + r * math.cos(a1 + sweep * k / steps),
                 centre[1] + r * math.sin(a1 + sweep * k / steps))
                for k in range(steps + 1)]
    out.append(pts[-1])
    return out


def _dedupe(pts):
    """Drop repeated points, comparing position only so a per-corner
    radius rides along untouched."""
    out = [pts[0]]
    for p in pts[1:]:
        if math.hypot(p[0] - out[-1][0], p[1] - out[-1][1]) > 1e-6:
            out.append(p)
    return out


def _free_end(pt, closed):
    """A terminal is free -- and so gets a round cap -- unless it lands on
    the baseline or the cap height, where a rounded end would break the
    line the text sits on. Closed shapes never get caps at all."""
    if closed:
        return False
    y = pt[1]
    return not (abs(y) <= CAP_TOL or abs(y - CAP) <= CAP_TOL)


def _semicircle(centre, normal, h, steps=12):
    """Half circle from centre+normal*h round to centre-normal*h, bulging
    away from the stroke -- a round cap."""
    a0 = math.atan2(normal[1], normal[0])
    return [(centre[0] + h * math.cos(a0 - math.pi * k / steps),
             centre[1] + h * math.sin(a0 - math.pi * k / steps))
            for k in range(1, steps)]


def _offset_path(points, weight, radius=None):
    """Offset a centreline to a closed outline, mitring at corners so the
    shape stays connected. Ends are flat on the baseline and cap height,
    and rounded where the stroke sticks out on its own."""
    pts = _dedupe(_fillet(_dedupe(points), RADIUS if radius is None else radius))
    if len(pts) < 2:
        return []
    h = weight / 2.0

    def seg_normal(a, b):
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy) or 1.0
        return (-dy / length, dx / length)

    normals = [seg_normal(pts[i], pts[i + 1]) for i in range(len(pts) - 1)]

    def side(sign):
        f0 = _cfac(normals[0][0])
        out = [(pts[0][0] + sign * normals[0][0] * h * f0,
                pts[0][1] + sign * normals[0][1] * h * f0)]
        for i in range(1, len(pts) - 1):
            n1, n2 = normals[i - 1], normals[i]
            f1, f2 = _cfac(n1[0], n1[1]), _cfac(n2[0], n2[1])
            mx, my = n1[0] + n2[0], n1[1] + n2[1]
            m = math.hypot(mx, my)
            if m < 1e-9:                       # exact reversal; bevel it
                out.append((pts[i][0] + sign * n1[0] * h * f1,
                            pts[i][1] + sign * n1[1] * h * f1))
                out.append((pts[i][0] + sign * n2[0] * h * f2,
                            pts[i][1] + sign * n2[1] * h * f2))
                continue
            mx, my = mx / m, my / m
            fm = _cfac(mx, my)
            cos_half = mx * n1[0] + my * n1[1]
            scale = 1.0 / max(cos_half, 1e-6)
            if scale > MITER_LIMIT:            # too sharp; bevel instead
                out.append((pts[i][0] + sign * n1[0] * h * f1,
                            pts[i][1] + sign * n1[1] * h * f1))
                out.append((pts[i][0] + sign * n2[0] * h * f2,
                            pts[i][1] + sign * n2[1] * h * f2))
            else:
                out.append((pts[i][0] + sign * mx * h * scale * fm,
                            pts[i][1] + sign * my * h * scale * fm))
        fl = _cfac(normals[-1][0])
        out.append((pts[-1][0] + sign * normals[-1][0] * h * fl,
                    pts[-1][1] + sign * normals[-1][1] * h * fl))
        return out

    h_ = h
    closed = math.hypot(pts[0][0] - pts[-1][0], pts[0][1] - pts[-1][1]) < 1e-6
    left, right = side(1), side(-1)
    out = list(left)
    if _free_end(pts[-1], closed):
        out += _semicircle(pts[-1], normals[-1], h_)
    out += right[::-1]
    if _free_end(pts[0], closed):
        out += _semicircle(pts[0], (-normals[0][0], -normals[0][1]), h_)
    return out


def _fillet_closed(pts, radius):
    """Fillet a closed loop, treating the seam as a corner like any other."""
    n = len(pts)
    out = []
    for i in range(n):
        p, a, b = pts[i], pts[(i - 1) % n], pts[(i + 1) % n]
        here = p[2] if len(p) > 2 else radius
        ux, uy = a[0] - p[0], a[1] - p[1]
        vx, vy = b[0] - p[0], b[1] - p[1]
        lu = math.hypot(ux, uy) or 1.0
        lv = math.hypot(vx, vy) or 1.0
        ux, uy, vx, vy = ux / lu, uy / lu, vx / lv, vy / lv
        ang = math.acos(max(-1.0, min(1.0, ux * vx + uy * vy)))
        if here <= 0 or ang < 1e-3 or abs(math.pi - ang) < 1e-3:
            out.append((p[0], p[1]))
            continue
        d = min(here / math.tan(ang / 2), lu * 0.5, lv * 0.5)
        r = d * math.tan(ang / 2)
        t1 = (p[0] + ux * d, p[1] + uy * d)
        t2 = (p[0] + vx * d, p[1] + vy * d)
        bx, by = ux + vx, uy + vy
        lb = math.hypot(bx, by) or 1.0
        centre = (p[0] + bx / lb * (r / math.sin(ang / 2)),
                  p[1] + by / lb * (r / math.sin(ang / 2)))
        a1 = math.atan2(t1[1] - centre[1], t1[0] - centre[0])
        a2 = math.atan2(t2[1] - centre[1], t2[0] - centre[0])
        sweep = (a2 - a1 + math.pi) % (2 * math.pi) - math.pi
        steps = max(6, int(abs(sweep) / 0.09))
        out += [(centre[0] + r * math.cos(a1 + sweep * k / steps),
                 centre[1] + r * math.sin(a1 + sweep * k / steps))
                for k in range(steps + 1)]
    return out


def _offset_closed(points, weight, radius):
    """Offset a closed centreline into a ring: an outer contour and a
    reversed inner one. Every vertex is mitred, including the seam, so
    the loop has no join in it."""
    corners = _dedupe(points)
    # Drop the repeated closing point before filleting, or the seam becomes
    # a degenerate zero-length corner and skews the offset.
    if len(corners) > 1 and math.hypot(corners[0][0] - corners[-1][0],
                                       corners[0][1] - corners[-1][1]) < 1e-6:
        corners = corners[:-1]
    pts = _dedupe(_fillet_closed(corners, radius))
    if len(pts) > 1 and math.hypot(pts[0][0] - pts[-1][0],
                                   pts[0][1] - pts[-1][1]) < 1e-6:
        pts = pts[:-1]
    n = len(pts)
    if n < 3:
        return []
    h = weight / 2.0
    norms = []
    for i in range(n):
        dx = pts[(i + 1) % n][0] - pts[i][0]
        dy = pts[(i + 1) % n][1] - pts[i][1]
        length = math.hypot(dx, dy) or 1.0
        norms.append((-dy / length, dx / length))

    def side(sign):
        out = []
        for i in range(n):
            n1, n2 = norms[(i - 1) % n], norms[i]
            f1, f2 = _cfac(n1[0], n1[1]), _cfac(n2[0], n2[1])
            mx, my = n1[0] + n2[0], n1[1] + n2[1]
            m = math.hypot(mx, my)
            if m < 1e-9:
                out.append((pts[i][0] + sign * n1[0] * h * f1,
                            pts[i][1] + sign * n1[1] * h * f1))
                out.append((pts[i][0] + sign * n2[0] * h * f2,
                            pts[i][1] + sign * n2[1] * h * f2))
                continue
            mx, my = mx / m, my / m
            fm = _cfac(mx, my)
            scale = 1.0 / max(mx * n1[0] + my * n1[1], 1e-6)
            if scale > MITER_LIMIT:
                out.append((pts[i][0] + sign * n1[0] * h * f1,
                            pts[i][1] + sign * n1[1] * h * f1))
                out.append((pts[i][0] + sign * n2[0] * h * f2,
                            pts[i][1] + sign * n2[1] * h * f2))
            else:
                out.append((pts[i][0] + sign * mx * h * scale * fm,
                            pts[i][1] + sign * my * h * scale * fm))
        return out

    # Which side is outside depends on the loop's winding, so decide by
    # area rather than assuming a sign.
    a, b = side(1), side(-1)

    def area(poly):
        return abs(0.5 * sum(poly[i][0] * poly[(i + 1) % len(poly)][1]
                             - poly[(i + 1) % len(poly)][0] * poly[i][1]
                             for i in range(len(poly))))

    return [a, b] if area(a) > area(b) else [b, a]


def _circle(cx, cy, r, n=36):
    return [(cx + r * math.cos(2 * math.pi * i / n),
             cy + r * math.sin(2 * math.pi * i / n)) for i in range(n)]


def _clockwise(poly):
    area = sum((poly[i][0] * poly[(i + 1) % len(poly)][1]
                - poly[(i + 1) % len(poly)][0] * poly[i][1])
               for i in range(len(poly)))
    return poly if area < 0 else poly[::-1]


def _trim_from_stave(pts, weight):
    """Shorten a centreline whose first/last point sits on the stave, so
    the limb's ink clears the stave's ink by DETACH."""
    cut = weight + DETACH        # half stave + gap + half limb
    def trim(seq):
        acc = 0.0
        for i in range(len(seq) - 1):
            seg = math.hypot(seq[i+1][0]-seq[i][0], seq[i+1][1]-seq[i][1])
            if acc + seg >= cut:
                t = (cut - acc) / (seg or 1.0)
                new0 = (seq[i][0] + (seq[i+1][0]-seq[i][0])*t,
                        seq[i][1] + (seq[i+1][1]-seq[i][1])*t)
                return [new0] + list(seq[i+1:])
            acc += seg
        return list(seq)
    out = list(pts)
    if abs(out[0][0]) < 1e-6:
        out = trim(out)
    if abs(out[-1][0]) < 1e-6:
        out = trim(out[::-1])[::-1]
    return out


def _extend_into_stave(pts, weight):
    """A limb whose end sits exactly on the stave centreline gets a butt
    cap cut perpendicular to its own direction -- against the stave's
    flat end that leaves a sliver of daylight at the junction. Push such
    ends INTO the stave so the two inks overlap and nothing can crack."""
    reach = weight * 0.6
    out = list(pts)
    if abs(out[0][0]) < 1e-6 and len(out) > 1:
        dx, dy = out[1][0] - out[0][0], out[1][1] - out[0][1]
        L = math.hypot(dx, dy) or 1.0
        out[0] = (out[0][0] - dx / L * reach, out[0][1] - dy / L * reach)
    if abs(out[-1][0]) < 1e-6 and len(out) > 1:
        dx, dy = out[-2][0] - out[-1][0], out[-2][1] - out[-1][1]
        L = math.hypot(dx, dy) or 1.0
        out[-1] = (out[-1][0] - dx / L * reach, out[-1][1] - dy / L * reach)
    return out


def contours(elements, weight=WEIGHT, curve=CURVE, radius=None):
    """Turn one glyph's skeleton into a list of closed contours.

    Winding is fixed as each contour is added: solids one way, holes the
    other. Do not normalise afterwards -- a blanket pass would turn the
    holes back into solids."""
    r = RADIUS if radius is None else radius
    out = []

    def add(poly, hole=False):
        if len(poly) > 2:
            out.append(_clockwise(poly)[::-1] if hole else _clockwise(poly))
    for e in elements:
        kind = e[0]
        if kind == "S":
            add(_offset_path([(0, 0), (0, CAP)], weight, r))
        elif kind == "V":
            _, x, y0, y1 = e
            add(_offset_path([(x, y0), (x, y1)], weight, r))
        elif kind == "L":
            _, x0, y0, x1, y1 = e
            pts = [(x0, y0), (x1, y1)]
            if DETACH:
                pts = _trim_from_stave(pts, weight)
            else:
                pts = _extend_into_stave(pts, weight)
            add(_offset_path(pts, weight, r))
        elif kind == "C":
            x0, y0, x1, y1 = e[1:5]
            sign = e[5] if len(e) > 5 else 1
            add(_offset_path(_bow(x0, y0, x1, y1, curve * sign), weight, r))
        elif kind == "P":
            pts = _expand(e[1], curve)
            closed_p = math.hypot(pts[0][0] - pts[-1][0], pts[0][1] - pts[-1][1]) < 1e-6
            if DETACH and not closed_p:
                pts = _trim_from_stave(pts, weight)
            elif not closed_p:
                pts = _extend_into_stave(pts, weight)
            if closed_p:
                ring = _offset_closed(pts, weight, r)
                if ring:
                    add(ring[0])
                    add(ring[1], hole=True)
                continue
            add(_offset_path(pts, weight, r))
        elif kind == "A":
            p0, c, p2 = e[1]
            add(_offset_path(_quad(p0, c, p2), weight, r))
        elif kind == "O":
            _, x, y, r = e
            add(_circle(x, y, r))
        elif kind == "D":
            _, x, y, r = e
            add(_circle(x, y, r, n=48))
        elif kind == "R":
            _, x, y, r = e
            ring = _offset_closed(_circle(x, y, r, n=48), weight, 0)
            if ring:
                add(ring[0])
                add(ring[1], hole=True)
    if SERIF:
        # A serif only goes on a FREE end. If another stroke's centreline
        # runs through the serif's footprint -- t and d's bracket over the
        # top, r and q's arm meeting the cap -- the serif would stamp over
        # ink that is already there.
        def _others(skip):
            out = []
            for o in elements:
                if o is skip:
                    continue
                k2 = o[0]
                if k2 == "S":
                    out.append([(0, 0), (0, CAP)])
                elif k2 == "V":
                    out.append([(o[1], o[2]), (o[1], o[3])])
                elif k2 == "L":
                    out.append([(o[1], o[2]), (o[3], o[4])])
                elif k2 == "P":
                    out.append(_expand(o[1], curve))
                elif k2 == "A":
                    out.append(_quad(*o[1]))
            return out

        def _blocked(xs, base, skip):
            reach_x = SERIF_LEN + weight / 2
            reach_y = (BRACKET_H if SERIF_STYLE == "bracketed"
                       else weight * 1.5)
            for poly in _others(skip):
                for i in range(len(poly) - 1):
                    a, b = poly[i], poly[i + 1]
                    steps = max(1, int(math.hypot(b[0] - a[0], b[1] - a[1]) / 20))
                    for t_ in range(steps + 1):
                        q = (a[0] + (b[0] - a[0]) * t_ / steps,
                             a[1] + (b[1] - a[1]) * t_ / steps)
                        if abs(q[0] - xs) < reach_x and abs(q[1] - base) < reach_y:
                            return True
            return False

        for e in elements:
            if e[0] == "S":
                xs, y0, y1 = 0, 0, CAP
            elif e[0] == "V":
                xs, y0, y1 = e[1], e[2], e[3]
            else:
                continue
            hw = weight / 2
            for y in (y0, y1):
                if y <= CAP_TOL:
                    base, up = 0, 1                  # a foot on the baseline
                elif y >= CAP - CAP_TOL:
                    base, up = CAP, -1               # a head on the cap
                else:
                    continue
                if _blocked(xs, base, e):
                    continue
                if SERIF_STYLE == "bracketed":
                    # Thin base; each side sweeps up into the stem along a
                    # quadratic bracket, the way an antikva serif is cut.
                    L, S, B = SERIF_LEN, SERIF_H, BRACKET_H
                    right = _quad((xs + L, base + up * S),
                                  (xs + hw, base + up * S),
                                  (xs + hw, base + up * B), n=10)
                    left = _quad((xs - hw, base + up * B),
                                 (xs - hw, base + up * S),
                                 (xs - L, base + up * S), n=10)
                    poly = ([(xs - L, base), (xs + L, base)] + right +
                            [(xs + hw, base + up * B)] + left)
                    add(poly)
                else:
                    bar = [(xs - SERIF_LEN, base + up * hw),
                           (xs + SERIF_LEN, base + up * hw)]
                    add(_offset_path(bar, weight, r))
    return out


# --- font assembly ---------------------------------------------------

def build(path, family="Runa", weight=WEIGHT, curve=CURVE, side=SIDE,
          radius=None):
    """Compile the skeletons into a TrueType font at `path`."""
    import os
    import sys
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import runes
    from fontTools.fontBuilder import FontBuilder
    from fontTools.pens.ttGlyphPen import TTGlyphPen

    targets = {runes.TABLE[c]: GLYPHS[c] for c in GLYPHS}
    targets.update(PUNCT)

    order = [".notdef", "space"]
    glyphs, metrics, cmap = {}, {}, {}
    glyphs[".notdef"] = TTGlyphPen(None).glyph()
    metrics[".notdef"] = (600, 0)
    glyphs["space"] = TTGlyphPen(None).glyph()
    metrics["space"] = (360, 0)
    cmap[0x20] = "space"

    shear = math.tan(math.radians(SLANT))
    for ch, elements in targets.items():
        cs = contours(elements, weight, curve, radius)
        if shear:
            cs = [[(q[0] + q[1] * shear, q[1]) for q in c] for c in cs]
        xs = [p[0] for c in cs for p in c]
        minx, maxx = (min(xs), max(xs)) if xs else (0, 0)
        shift = side - minx
        pen = TTGlyphPen(None)
        for c in cs:
            pen.moveTo((round(c[0][0] + shift), round(c[0][1])))
            for x, y in c[1:]:
                pen.lineTo((round(x + shift), round(y)))
            pen.closePath()
        name = f"uni{ord(ch):04X}"
        glyphs[name] = pen.glyph()
        metrics[name] = (round(maxx - minx + side * 2), side)
        cmap[ord(ch)] = name
        order.append(name)

    fb = FontBuilder(UPEM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    fb.setupNameTable({
        "familyName": family, "styleName": "Regular",
        "uniqueFontIdentifier": f"{family}-Regular",
        "fullName": f"{family} Regular", "psName": f"{family}-Regular",
        "version": "Version 1.000",
        "copyright": "Generated by runefont.py. SIL Open Font License 1.1.",
        "licenseDescription": "Licensed under the SIL Open Font License 1.1.",
    })
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800,
                usWinDescent=200, sCapHeight=CAP, achVendID="RUNA")
    fb.setupPost()
    fb.save(path)
    return path


if __name__ == "__main__":
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/Runa-Regular.ttf"
    build(out)
    print("wrote", out)
