#!/usr/bin/env python3
"""Generate a runic typeface from skeletons, parametrically.

Runes are a stave plus branches, which means they can be *described*
rather than drawn: each glyph below is a list of strokes on a shared
grid, and the outlines are generated by offsetting those centrelines.
Curvature, weight and spacing are dials, so a redesign is a rebuild
rather than a redraw.

Skeletons were derived from Noto Sans Runic's own outlines (cap height
714, stroke weight 92) so the letterforms stay correct; the parameters
are then free to depart from it.

Two things matter for the result not looking broken:

* A shape that turns a corner is ONE path offset as a whole, with
  mitred joins. Offsetting each segment separately and stacking them
  leaves a notch on the outside of every corner.
* Overlapping strokes are not booleaned. TrueType fills by nonzero
  winding, so contours wound the same direction merge for free -- which
  is why this needs no boolean-operations library.
"""

import math

CAP = 714          # cap height, matching Noto Sans Runic
UPEM = 1000

# --- the dials -------------------------------------------------------
WEIGHT = 76        # stroke thickness. Noto is 92; lighter reads airier.
CURVE = 0.60       # 0 = straight branches, 1 = strongly bowed
SIDE = 120         # sidebearing each side. Noto is ~96; wider = airier.
DOT_R = 52         # radius of the dot on dotted runes
DOT_X = 108        # how far the dot sits from the stave centre
SEGMENTS = 20      # sampling resolution for curved strokes
MITER_LIMIT = 3.4  # beyond this a sharp corner bevels instead of spiking
CAP_TOL = 30       # how close to the baseline or cap height still counts as
                   # "landing on the line", and so stays flat-ended
RADIUS = 40        # default corner radius on the centreline. 0 = sharp
                   # mitre; small = a hard corner; large = a soft sweep.
                   # Any single point may override it as (x, y, r).

# --- skeletons -------------------------------------------------------
# x is relative to the stave centre; y is absolute from the baseline.
#   S                 full-height stave at x=0
#   V x y0 y1         vertical segment
#   L x0 y0 x1 y1     straight stroke
#   C x0 y0 x1 y1 [s] bowed stroke; s=-1 bows the other way. Branches
#                     bow AWAY from the stave, or they close over the dot
#                     that separates g from k and v from f.
#   P [pts]           connected path, mitred at every corner. Entries are
#                     (x,y), (x,y,r) to give that one corner its own
#                     radius, or ("c",x,y,sign) to bow into that point.
#   A [p0,ctrl,p2]    smooth arc through a quadratic control point
#   O x y r           dot
#   D x y r           filled disc (the bowl of c)
# Orthogonal construction: every bend is a right angle, softened only by
# RADIUS. Runes are natively staves and diagonals -- carvers avoided
# horizontals because they run along the wood grain and vanish -- so this
# is a deliberately modern reading, not a historical one. Where forcing
# right angles would collapse a rune into its Latin lookalike (b, r, s)
# the shape is redrawn to stay distinct rather than left to converge.
# A corner is a full quarter circle when its radius equals half the
# shorter adjacent segment: the arc then consumes half of each, leaving
# equal straight tails. Side branches are built with equal-length
# segments so that maximum lands exactly on a quarter circle.
STUB = 170         # each leg of a side branch
STUB_R = 85        # = STUB/2, so every side branch is a quarter circle
GAP = 150          # distance between the two arms of f and v. For the gap
                   # to stay even round the bend the outer radius must be
                   # the inner plus GAP; that puts both arcs on one centre.

GLYPHS = {
    "a": [("S",), ("P", [(0, 430), (-STUB, 430, STUB_R), (-STUB, 430 - STUB)])],
    # Bowls meet the stave top, middle and bottom, as bjarkan always has.
    # It reads close to a squared B because the two letters share an
    # ancestor; that is convergence, not an error.
    "b": [("S",), ("P", [(0, 714), (300, 714), (300, 392), (0, 392)]),
          ("P", [(0, 322), (300, 322), (300, 0), (0, 0)])],
    "c": [("D", 0, 366, 100), ("V", 0, 430, CAP)],
    "d": [("S",), ("P", [(-200, 514), (-200, CAP, 100), (200, CAP, 100), (200, 514)]),
          ("O", DOT_X, 340, DOT_R)],
    "e": [("S",), ("O", DOT_X, 370, DOT_R)],
    # Both arms GAP apart on the straights, radii GAP apart at the bend,
    # so the two arcs share a centre and the gap never varies. The outer
    # corner is a full quarter circle; the inner cannot also be, because
    # it must leave room for the outer one.
    "f": [("S",), ("P", [(0, 300), (400, 300, 125), (400, 700)]),
          ("P", [(0, 150), (550, 150, 275), (550, 700)])],
    "g": [("S",), ("P", [(0, 300), (400, 300, 125), (400, 700)]),
          ("O", 185, 530, DOT_R)],
    "h": [("S",), ("P", [(-190, 250, 100), (190, 250, 100), (190, 490, 100),
                         (-190, 490, 100), (-190, 250)])],
    "i": [("S",)],
    # Two opposed hooks. Where they run alongside each other the arms are
    # 170 apart -- the same spacing as everywhere else -- so the lines stay
    # parallel instead of colliding.
    "j": [("P", [(60, CAP), (-190, CAP, 125), (-190, 374, 125), (60, 374)]),
          ("P", [(-60, 204), (190, 204, 125), (190, 544, 125), (-60, 544)])],
    # kaun is fé with one arm, so it uses fé's inner arm unchanged.
    "k": [("S",), ("P", [(0, 300), (400, 300, 125), (400, 700)])],
    "l": [("S",), ("P", [(0, 640), (STUB, 640, STUB_R), (STUB, 640 - STUB)])],
    "m": [("S",), ("P", [(-269, 700), (-269, 470, 115), (269, 470, 115), (269, 700)])],
    "n": [("S",), ("P", [(0, 430), (STUB, 430, STUB_R), (STUB, 430 - STUB)])],
    "o": [("S",), ("P", [(0, 520), (-STUB, 520, STUB_R), (-STUB, 350)]),
          ("P", [(0, 290), (-STUB, 290, STUB_R), (-STUB, 120)])],
    "p": [("S",), ("P", [(0, 714), (300, 714), (300, 392), (0, 392)]),
          ("P", [(0, 322), (300, 322), (300, 0), (0, 0)]),
          ("O", 150, 545, 46), ("O", 150, 175, 46)],
    "q": [("S",), ("P", [(0, 714), (-262, 714), (-262, 228), (0, 228)])],
    # Bowl closed at the top only, then a single leg dropping the full
    # height -- keeps reið distinct from an orthogonal A or P.
    "r": [("S",), ("P", [(0, 714), (275, 714), (275, 0)]),
          ("P", [(0, 470), (275, 470)])],
    "s": [("P", [(-184, CAP), (-184, 392), (184, 392), (184, 0)])],
    "t": [("S",), ("P", [(-200, 514), (-200, CAP, 100), (200, CAP, 100), (200, 514)])],
    # Radius = half the horizontal, so the two quarter circles meet at the
    # top centre and the whole cap is one continuous semicircle.
    "u": [("P", [(-230, 0), (-230, CAP, 230), (230, CAP, 230), (230, 0)])],
    "v": [("S",), ("P", [(0, 300), (400, 300, 125), (400, 700)]),
          ("P", [(0, 150), (550, 150, 275), (550, 700)]),
          ("O", 165, 560, DOT_R)],
    # The inner arch springs from the outer's own left leg, so it cannot be
    # truly concentric with it; the even gap is held on the parallel
    # verticals instead.
    "w": [("P", [(-230, 0), (-230, CAP, 230), (230, CAP, 230), (230, 0)]),
          ("P", [(-230, 330), (90, 330, 110), (90, 0)])],
    "x": [("P", [(-184, CAP), (-184, 392), (184, 392), (184, 0)]),
          ("L", -372, 600, 2, 600), ("L", -2, 120, 372, 120)],
    "y": [("P", [(-230, 0), (-230, CAP, 230), (230, CAP, 230), (230, 0)]),
          ("O", 0, 300, DOT_R)],
    "z": [("V", 0, 300, CAP),
          ("P", [(-196, 470), (-196, 300, 85), (196, 300, 85), (196, 470)])],
    "æ": [("S",), ("P", [(0, 430), (-STUB, 430, STUB_R), (-STUB, 430 - STUB)]),
          ("P", [(0, 430), (STUB, 430, STUB_R), (STUB, 430 + STUB)])],
    "ø": [("S",), ("P", [(0, 520), (-STUB, 520, STUB_R), (-STUB, 350)]),
          ("P", [(0, 290), (-STUB, 290, STUB_R), (-STUB, 120)]),
          ("P", [(0, 520), (STUB, 520, STUB_R), (STUB, 350)]),
          ("P", [(0, 290), (STUB, 290, STUB_R), (STUB, 120)])],
    "å": [("S",), ("P", [(0, 520), (STUB, 520, STUB_R), (STUB, 350)]),
          ("P", [(0, 290), (STUB, 290, STUB_R), (STUB, 120)])],
}

PUNCT = {
    "᛫": [("O", 0, 357, 46)],
    "᛬": [("O", 0, 214, 46), ("O", 0, 500, 46)],
    "᛭": [("V", 0, 100, 614), ("L", -190, 357, 190, 357)],
}


# --- geometry --------------------------------------------------------

def _bow(x0, y0, x1, y1, amount, n=SEGMENTS):
    """Sample a stroke bowed perpendicular to its chord."""
    dx, dy = x1 - x0, y1 - y0
    length = math.hypot(dx, dy) or 1.0
    nx, ny = -dy / length, dx / length
    sag = amount * length * 0.28
    return [(x0 + dx * (i / n) + nx * sag * (4 * (i / n) * (1 - i / n)),
             y0 + dy * (i / n) + ny * sag * (4 * (i / n) * (1 - i / n)))
            for i in range(n + 1)]


def _quad(p0, c, p2, n=SEGMENTS):
    """Quadratic Bezier through a control point -- used for the arched
    tops (t, d) and the valleys (m, z, j), which must read as one
    continuous curve rather than two lines meeting at a point."""
    pts = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        pts.append((u * u * p0[0] + 2 * u * t * c[0] + t * t * p2[0],
                    u * u * p0[1] + 2 * u * t * c[1] + t * t * p2[1]))
    return pts


def _expand(pts, curve):
    """Turn a path description into a dense polyline."""
    out = [pts[0]]
    for item in pts[1:]:
        if item and item[0] == "c":
            _, x, y, sign = item
            out += _bow(out[-1][0], out[-1][1], x, y, curve * sign)[1:]
        else:
            out.append(item)
    return out


def _fillet(pts, radius):
    """Round every corner of a centreline.

    `radius` is the default; a point given as (x, y, r) overrides it for
    that corner alone, so one shape can mix hard and soft turns. The arc
    is cut into the two adjacent segments, so the corner keeps its
    direction but stops being a point."""
    if len(pts) < 3:
        return pts
    out = [pts[0]]
    for i in range(1, len(pts) - 1):
        p, a, b = pts[i], pts[i - 1], pts[i + 1]
        here = p[2] if len(p) > 2 else radius
        if here <= 0:
            out.append(p)
            continue
        ux, uy = a[0] - p[0], a[1] - p[1]
        vx, vy = b[0] - p[0], b[1] - p[1]
        lu = math.hypot(ux, uy) or 1.0
        lv = math.hypot(vx, vy) or 1.0
        ux, uy, vx, vy = ux / lu, uy / lu, vx / lv, vy / lv
        cosang = max(-1.0, min(1.0, ux * vx + uy * vy))
        ang = math.acos(cosang)                 # interior angle at p
        if ang < 1e-3 or abs(math.pi - ang) < 1e-3:
            out.append(p)                        # straight through
            continue
        # A corner cannot eat more than half of either adjacent segment --
        # at exactly half, two corners on one segment meet and the segment
        # is fully consumed, which is the roundest a corner can get. Ask
        # for more and you simply get this.
        d = min(here / math.tan(ang / 2), lu * 0.5, lv * 0.5)
        r = d * math.tan(ang / 2)
        t1 = (p[0] + ux * d, p[1] + uy * d)
        t2 = (p[0] + vx * d, p[1] + vy * d)
        bx, by = ux + vx, uy + vy
        lb = math.hypot(bx, by) or 1.0
        centre = (p[0] + bx / lb * (r / math.sin(ang / 2)),
                  p[1] + by / lb * (r / math.sin(ang / 2)))
        a1 = math.atan2(t1[1] - centre[1], t1[0] - centre[0])
        a2 = math.atan2(t2[1] - centre[1], t2[0] - centre[0])
        sweep = (a2 - a1 + math.pi) % (2 * math.pi) - math.pi
        steps = max(3, int(abs(sweep) / 0.22))
        out += [(centre[0] + r * math.cos(a1 + sweep * k / steps),
                 centre[1] + r * math.sin(a1 + sweep * k / steps))
                for k in range(steps + 1)]
    out.append(pts[-1])
    return out


def _dedupe(pts):
    """Drop repeated points, comparing position only so a per-corner
    radius rides along untouched."""
    out = [pts[0]]
    for p in pts[1:]:
        if math.hypot(p[0] - out[-1][0], p[1] - out[-1][1]) > 1e-6:
            out.append(p)
    return out


def _free_end(pt, closed):
    """A terminal is free -- and so gets a round cap -- unless it lands on
    the baseline or the cap height, where a rounded end would break the
    line the text sits on. Closed shapes never get caps at all."""
    if closed:
        return False
    y = pt[1]
    return not (abs(y) <= CAP_TOL or abs(y - CAP) <= CAP_TOL)


def _semicircle(centre, normal, h, steps=12):
    """Half circle from centre+normal*h round to centre-normal*h, bulging
    away from the stroke -- a round cap."""
    a0 = math.atan2(normal[1], normal[0])
    return [(centre[0] + h * math.cos(a0 - math.pi * k / steps),
             centre[1] + h * math.sin(a0 - math.pi * k / steps))
            for k in range(1, steps)]


def _offset_path(points, weight, radius=None):
    """Offset a centreline to a closed outline, mitring at corners so the
    shape stays connected. Ends are flat on the baseline and cap height,
    and rounded where the stroke sticks out on its own."""
    pts = _dedupe(_fillet(_dedupe(points), RADIUS if radius is None else radius))
    if len(pts) < 2:
        return []
    h = weight / 2.0

    def seg_normal(a, b):
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy) or 1.0
        return (-dy / length, dx / length)

    normals = [seg_normal(pts[i], pts[i + 1]) for i in range(len(pts) - 1)]

    def side(sign):
        out = [(pts[0][0] + sign * normals[0][0] * h,
                pts[0][1] + sign * normals[0][1] * h)]
        for i in range(1, len(pts) - 1):
            n1, n2 = normals[i - 1], normals[i]
            mx, my = n1[0] + n2[0], n1[1] + n2[1]
            m = math.hypot(mx, my)
            if m < 1e-9:                       # exact reversal; bevel it
                out.append((pts[i][0] + sign * n1[0] * h,
                            pts[i][1] + sign * n1[1] * h))
                out.append((pts[i][0] + sign * n2[0] * h,
                            pts[i][1] + sign * n2[1] * h))
                continue
            mx, my = mx / m, my / m
            cos_half = mx * n1[0] + my * n1[1]
            scale = 1.0 / max(cos_half, 1e-6)
            if scale > MITER_LIMIT:            # too sharp; bevel instead
                out.append((pts[i][0] + sign * n1[0] * h,
                            pts[i][1] + sign * n1[1] * h))
                out.append((pts[i][0] + sign * n2[0] * h,
                            pts[i][1] + sign * n2[1] * h))
            else:
                out.append((pts[i][0] + sign * mx * h * scale,
                            pts[i][1] + sign * my * h * scale))
        out.append((pts[-1][0] + sign * normals[-1][0] * h,
                    pts[-1][1] + sign * normals[-1][1] * h))
        return out

    h_ = h
    closed = math.hypot(pts[0][0] - pts[-1][0], pts[0][1] - pts[-1][1]) < 1e-6
    left, right = side(1), side(-1)
    out = list(left)
    if _free_end(pts[-1], closed):
        out += _semicircle(pts[-1], normals[-1], h_)
    out += right[::-1]
    if _free_end(pts[0], closed):
        out += _semicircle(pts[0], (-normals[0][0], -normals[0][1]), h_)
    return out


def _fillet_closed(pts, radius):
    """Fillet a closed loop, treating the seam as a corner like any other."""
    n = len(pts)
    out = []
    for i in range(n):
        p, a, b = pts[i], pts[(i - 1) % n], pts[(i + 1) % n]
        here = p[2] if len(p) > 2 else radius
        ux, uy = a[0] - p[0], a[1] - p[1]
        vx, vy = b[0] - p[0], b[1] - p[1]
        lu = math.hypot(ux, uy) or 1.0
        lv = math.hypot(vx, vy) or 1.0
        ux, uy, vx, vy = ux / lu, uy / lu, vx / lv, vy / lv
        ang = math.acos(max(-1.0, min(1.0, ux * vx + uy * vy)))
        if here <= 0 or ang < 1e-3 or abs(math.pi - ang) < 1e-3:
            out.append((p[0], p[1]))
            continue
        d = min(here / math.tan(ang / 2), lu * 0.5, lv * 0.5)
        r = d * math.tan(ang / 2)
        t1 = (p[0] + ux * d, p[1] + uy * d)
        t2 = (p[0] + vx * d, p[1] + vy * d)
        bx, by = ux + vx, uy + vy
        lb = math.hypot(bx, by) or 1.0
        centre = (p[0] + bx / lb * (r / math.sin(ang / 2)),
                  p[1] + by / lb * (r / math.sin(ang / 2)))
        a1 = math.atan2(t1[1] - centre[1], t1[0] - centre[0])
        a2 = math.atan2(t2[1] - centre[1], t2[0] - centre[0])
        sweep = (a2 - a1 + math.pi) % (2 * math.pi) - math.pi
        steps = max(3, int(abs(sweep) / 0.22))
        out += [(centre[0] + r * math.cos(a1 + sweep * k / steps),
                 centre[1] + r * math.sin(a1 + sweep * k / steps))
                for k in range(steps + 1)]
    return out


def _offset_closed(points, weight, radius):
    """Offset a closed centreline into a ring: an outer contour and a
    reversed inner one. Every vertex is mitred, including the seam, so
    the loop has no join in it."""
    corners = _dedupe(points)
    # Drop the repeated closing point before filleting, or the seam becomes
    # a degenerate zero-length corner and skews the offset.
    if len(corners) > 1 and math.hypot(corners[0][0] - corners[-1][0],
                                       corners[0][1] - corners[-1][1]) < 1e-6:
        corners = corners[:-1]
    pts = _dedupe(_fillet_closed(corners, radius))
    if len(pts) > 1 and math.hypot(pts[0][0] - pts[-1][0],
                                   pts[0][1] - pts[-1][1]) < 1e-6:
        pts = pts[:-1]
    n = len(pts)
    if n < 3:
        return []
    h = weight / 2.0
    norms = []
    for i in range(n):
        dx = pts[(i + 1) % n][0] - pts[i][0]
        dy = pts[(i + 1) % n][1] - pts[i][1]
        length = math.hypot(dx, dy) or 1.0
        norms.append((-dy / length, dx / length))

    def side(sign):
        out = []
        for i in range(n):
            n1, n2 = norms[(i - 1) % n], norms[i]
            mx, my = n1[0] + n2[0], n1[1] + n2[1]
            m = math.hypot(mx, my)
            if m < 1e-9:
                out.append((pts[i][0] + sign * n1[0] * h,
                            pts[i][1] + sign * n1[1] * h))
                out.append((pts[i][0] + sign * n2[0] * h,
                            pts[i][1] + sign * n2[1] * h))
                continue
            mx, my = mx / m, my / m
            scale = 1.0 / max(mx * n1[0] + my * n1[1], 1e-6)
            if scale > MITER_LIMIT:
                out.append((pts[i][0] + sign * n1[0] * h,
                            pts[i][1] + sign * n1[1] * h))
                out.append((pts[i][0] + sign * n2[0] * h,
                            pts[i][1] + sign * n2[1] * h))
            else:
                out.append((pts[i][0] + sign * mx * h * scale,
                            pts[i][1] + sign * my * h * scale))
        return out

    # Which side is outside depends on the loop's winding, so decide by
    # area rather than assuming a sign.
    a, b = side(1), side(-1)

    def area(poly):
        return abs(0.5 * sum(poly[i][0] * poly[(i + 1) % len(poly)][1]
                             - poly[(i + 1) % len(poly)][0] * poly[i][1]
                             for i in range(len(poly))))

    return [a, b] if area(a) > area(b) else [b, a]


def _circle(cx, cy, r, n=36):
    return [(cx + r * math.cos(2 * math.pi * i / n),
             cy + r * math.sin(2 * math.pi * i / n)) for i in range(n)]


def _clockwise(poly):
    area = sum((poly[i][0] * poly[(i + 1) % len(poly)][1]
                - poly[(i + 1) % len(poly)][0] * poly[i][1])
               for i in range(len(poly)))
    return poly if area < 0 else poly[::-1]


def contours(elements, weight=WEIGHT, curve=CURVE, radius=None):
    """Turn one glyph's skeleton into a list of closed contours.

    Winding is fixed as each contour is added: solids one way, holes the
    other. Do not normalise afterwards -- a blanket pass would turn the
    holes back into solids."""
    r = RADIUS if radius is None else radius
    out = []

    def add(poly, hole=False):
        if len(poly) > 2:
            out.append(_clockwise(poly)[::-1] if hole else _clockwise(poly))
    for e in elements:
        kind = e[0]
        if kind == "S":
            add(_offset_path([(0, 0), (0, CAP)], weight, r))
        elif kind == "V":
            _, x, y0, y1 = e
            add(_offset_path([(x, y0), (x, y1)], weight, r))
        elif kind == "L":
            _, x0, y0, x1, y1 = e
            add(_offset_path([(x0, y0), (x1, y1)], weight, r))
        elif kind == "C":
            x0, y0, x1, y1 = e[1:5]
            sign = e[5] if len(e) > 5 else 1
            add(_offset_path(_bow(x0, y0, x1, y1, curve * sign), weight, r))
        elif kind == "P":
            pts = _expand(e[1], curve)
            if math.hypot(pts[0][0] - pts[-1][0], pts[0][1] - pts[-1][1]) < 1e-6:
                ring = _offset_closed(pts, weight, r)
                if ring:
                    add(ring[0])
                    add(ring[1], hole=True)
                continue
            add(_offset_path(pts, weight, r))
        elif kind == "A":
            p0, c, p2 = e[1]
            add(_offset_path(_quad(p0, c, p2), weight, r))
        elif kind == "O":
            _, x, y, r = e
            add(_circle(x, y, r))
        elif kind == "D":
            _, x, y, r = e
            add(_circle(x, y, r, n=48))
    return out


# --- font assembly ---------------------------------------------------

def build(path, family="Runa", weight=WEIGHT, curve=CURVE, side=SIDE,
          radius=None):
    """Compile the skeletons into a TrueType font at `path`."""
    import os
    import sys
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import runes
    from fontTools.fontBuilder import FontBuilder
    from fontTools.pens.ttGlyphPen import TTGlyphPen

    targets = {runes.TABLE[c]: GLYPHS[c] for c in GLYPHS}
    targets.update(PUNCT)

    order = [".notdef", "space"]
    glyphs, metrics, cmap = {}, {}, {}
    glyphs[".notdef"] = TTGlyphPen(None).glyph()
    metrics[".notdef"] = (600, 0)
    glyphs["space"] = TTGlyphPen(None).glyph()
    metrics["space"] = (360, 0)
    cmap[0x20] = "space"

    for ch, elements in targets.items():
        cs = contours(elements, weight, curve, radius)
        xs = [p[0] for c in cs for p in c]
        minx, maxx = (min(xs), max(xs)) if xs else (0, 0)
        shift = side - minx
        pen = TTGlyphPen(None)
        for c in cs:
            pen.moveTo((round(c[0][0] + shift), round(c[0][1])))
            for x, y in c[1:]:
                pen.lineTo((round(x + shift), round(y)))
            pen.closePath()
        name = f"uni{ord(ch):04X}"
        glyphs[name] = pen.glyph()
        metrics[name] = (round(maxx - minx + side * 2), side)
        cmap[ord(ch)] = name
        order.append(name)

    fb = FontBuilder(UPEM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    fb.setupNameTable({
        "familyName": family, "styleName": "Regular",
        "uniqueFontIdentifier": f"{family}-Regular",
        "fullName": f"{family} Regular", "psName": f"{family}-Regular",
        "version": "Version 1.000",
        "copyright": "Generated by runefont.py. SIL Open Font License 1.1.",
        "licenseDescription": "Licensed under the SIL Open Font License 1.1.",
    })
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800,
                usWinDescent=200, sCapHeight=CAP, achVendID="RUNA")
    fb.setupPost()
    fb.save(path)
    return path


if __name__ == "__main__":
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/Runa-Regular.ttf"
    build(out)
    print("wrote", out)
